name = "QuantumFockCore"
uuid = "c4c52a10-75be-47fa-9298-4f0d724bc661"
version = "0.2.0"
authors = ["loulamme "]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorSchemes = "3.30.0"
DifferentialEquations = "7.16.1"
Interpolations = "0.16.2"
IterTools = "1.10.0"
JLD2 = "0.5.15"
LinearAlgebra = "1.11.0"
OrdinaryDiffEq = "6.101.0"
Plots = "1.40.14"
ProgressMeter = "1.10.4"
Revise = "3.8.0"
SparseArrayKit = "0.4.1"
StaticArrays = "1.9.13"
