name = "QuantumFockCore"
uuid = "c4c52a10-75be-47fa-9298-4f0d724bc661"
version = "0.2.0"
authors = ["Louis Lammertyn"]

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Interpolations = "0.16.2"
IterTools = "1.10.0"
LinearAlgebra = "1.11.0"
ProgressMeter = "1.10.4"
Revise = "3.8.0"
SparseArrayKit = "0.4.1"
StaticArrays = "1.9.13"
